### ISSUE TITLE
请问 这个vpn怎么删掉？

### ISSUE THREAD

**Issue by annkoxx** [tomoncle/pptp-vpn-server#1]
请问 这个vpn怎么删掉？
就是怎么从ubu18.4内完全删除  也不运行

**Comment by tomoncle** [comment]
试试下面命令：

* 卸载软件包
    * 1. `sudo apt-get remove pptpd`
    * 2. `sudo apt-get remove --auto-remove pptpd`

* 卸载配置
    * 1. `sudo apt-get purge pptpd`
    * 2. `sudo apt-get purge --auto-remove pptpd`

* 恢复系统默认配置
    * 1. 清理 `iptables`
    * 2. 数据包转发是否关闭，自己视情况而定
